# Generated by Django 5.1.2 on 2024-12-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('detected_disease', models.CharField(max_length=255)),
                ('average_confidence', models.FloatField()),
                ('pesticides', models.TextField(blank=True, null=True)),
                ('precautions', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
